package exception;

public class Throw3 {
    public static void main(String[] args) {

        //if you write any statement after throw then it give compile time error
        throw new ArithmeticException();
       // System.out.println("hello");
    }
}
